# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SewApwXlToZx40dq53cjZwLZ3LR3zym_
"""

import folium
import pandas
data=pandas.read_csv("Volcanoes.txt")
lat=list(data["LAT"])
lon=list(data["LON"])
elev=list(data["ELEV"])
def color_producer(elevation):
  if elevation<1000:
    return 'green'
  elif 1000<=elevation<3000:
    return 'orange'
  else:
    return 'red'  
map=folium.Map(location=[38.2,-99.1],zoom_start=6,tiles="Mapbox Bright")
fgv=folium.FeatureGroup(name="Volcanoes")
for lt,ln,el in zip(lat,lon,elev):
    fgv.add_child(folium.CircleMarker(location=[lt,ln],radius=6,popup=str(el),icon=folium.Icon(color='green')))

fgp=folium.FeatureGroup(name="Population")

fgp.add_child(folium.GeoJson(data=open('world.json','r',encoding='utf-8-sig').read()))
style_function=lambda x:{'fillColor':'green' if x['properties']['POP2005']<10000000
else 'orange' if 10000000<= x['properties']['POP2005']<20000000 else 'red'                         }   
map.add_child(fgv)
map.add_child(fgp)
folium.LayerControl().add_to(map)
map.save("Map1.html")
   
map


